INSERT INTO role(nome) VALUES ('produto');
INSERT INTO role(nome) VALUES ('categoria');
INSERT INTO role(nome) VALUES ('promocoes');
INSERT INTO role(nome) VALUES ('destaques');
INSERT INTO role(nome) VALUES ('usuarios');
INSERT INTO role(nome) VALUES ('configuracao');
INSERT INTO role(nome) VALUES ('preferencias');
INSERT INTO role(nome) VALUES ('perfil');
INSERT INTO role(nome) VALUES ('materia_prima');
INSERT INTO role(nome) VALUES ('quantidade_materia_prima');
INSERT INTO role(nome) VALUES ('descricao_materia_prima');
INSERT INTO role(nome) VALUES ('fornecedor');
INSERT INTO role(nome) VALUES ('endereco');
INSERT INTO role(nome) VALUES ('contato');
INSERT INTO role(nome) VALUES ('unidade');
INSERT INTO role(nome) VALUES ('permissao');
INSERT INTO role(nome) VALUES ('geral');

INSERT INTO permission(nome) VALUES ('cadastra_produto');
INSERT INTO permission(nome) VALUES ('altera_produto');
INSERT INTO permission(nome) VALUES ('remove_produto');
INSERT INTO permission(nome) VALUES ('cadastra_categoria');
INSERT INTO permission(nome) VALUES ('altera_categoria');
INSERT INTO permission(nome) VALUES ('remove_categoria');
INSERT INTO permission(nome) VALUES ('cadastra_promocao');
INSERT INTO permission(nome) VALUES ('altera_promocao');
INSERT INTO permission(nome) VALUES ('remove_promocao');
INSERT INTO permission(nome) VALUES ('cadastra_destaque');
INSERT INTO permission(nome) VALUES ('altera_destaque');
INSERT INTO permission(nome) VALUES ('remove_destaque');
INSERT INTO permission(nome) VALUES ('cadastra_usuario');
INSERT INTO permission(nome) VALUES ('altera_usuario');
INSERT INTO permission(nome) VALUES ('remove_usuario');
INSERT INTO permission(nome) VALUES ('cadastra_configuracao');
INSERT INTO permission(nome) VALUES ('altera_configuracao');
INSERT INTO permission(nome) VALUES ('remove_configuracao');
INSERT INTO permission(nome) VALUES ('cadastra_preferencia');
INSERT INTO permission(nome) VALUES ('altera_preferencia');
INSERT INTO permission(nome) VALUES ('remove_preferencia');
INSERT INTO permission(nome) VALUES ('cadastra_perfil');
INSERT INTO permission(nome) VALUES ('altera_perfil');
INSERT INTO permission(nome) VALUES ('remove_perfil');
INSERT INTO permission(nome) VALUES ('cadastra_materia_prima');
INSERT INTO permission(nome) VALUES ('altera_materia_prima');
INSERT INTO permission(nome) VALUES ('remove_materia_prima');
INSERT INTO permission(nome) VALUES ('cadastra_quantidade_materia_prima');
INSERT INTO permission(nome) VALUES ('altera_quantidade_materia_prima');
INSERT INTO permission(nome) VALUES ('remove_quantidade_materia_prima');
INSERT INTO permission(nome) VALUES ('cadastra_descricao_materia_prima');
INSERT INTO permission(nome) VALUES ('altera_descricao_materia_prima');
INSERT INTO permission(nome) VALUES ('remove_descricao_materia_prima');
INSERT INTO permission(nome) VALUES ('cadastra_fornecedor');
INSERT INTO permission(nome) VALUES ('altera_fornecedor');
INSERT INTO permission(nome) VALUES ('remove_fornecedor');
INSERT INTO permission(nome) VALUES ('cadastra_endereco');
INSERT INTO permission(nome) VALUES ('altera_endereco');
INSERT INTO permission(nome) VALUES ('remove_endereco');
INSERT INTO permission(nome) VALUES ('cadastra_contato');
INSERT INTO permission(nome) VALUES ('altera_contato');
INSERT INTO permission(nome) VALUES ('remove_contato');
INSERT INTO permission(nome) VALUES ('cadastra_unidade');
INSERT INTO permission(nome) VALUES ('altera_unidade');
INSERT INTO permission(nome) VALUES ('remove_unidade');
INSERT INTO permission(nome) VALUES ('cadastra_permissao');
INSERT INTO permission(nome) VALUES ('altera_permissao');
INSERT INTO permission(nome) VALUES ('remove_permissao');
INSERT INTO permission(nome) VALUES ('dashboard');

INSERT INTO role_permissions(fk_role, fk_permission) VALUES (1, 1);
INSERT INTO role_permissions(fk_role, fk_permission) VALUES (1, 2);
INSERT INTO role_permissions(fk_role, fk_permission) VALUES (1, 3);
INSERT INTO role_permissions(fk_role, fk_permission) VALUES (2, 4);
INSERT INTO role_permissions(fk_role, fk_permission) VALUES (2, 5);
INSERT INTO role_permissions(fk_role, fk_permission) VALUES (2, 6);
INSERT INTO role_permissions(fk_role, fk_permission) VALUES (3, 7);
INSERT INTO role_permissions(fk_role, fk_permission) VALUES (3, 8);
INSERT INTO role_permissions(fk_role, fk_permission) VALUES (3, 9);
INSERT INTO role_permissions(fk_role, fk_permission) VALUES (4, 10);
INSERT INTO role_permissions(fk_role, fk_permission) VALUES (4, 11);
INSERT INTO role_permissions(fk_role, fk_permission) VALUES (4, 12);
INSERT INTO role_permissions(fk_role, fk_permission) VALUES (5, 13);
INSERT INTO role_permissions(fk_role, fk_permission) VALUES (5, 14);
INSERT INTO role_permissions(fk_role, fk_permission) VALUES (5, 15);
INSERT INTO role_permissions(fk_role, fk_permission) VALUES (6, 16);
INSERT INTO role_permissions(fk_role, fk_permission) VALUES (6, 17);
INSERT INTO role_permissions(fk_role, fk_permission) VALUES (6, 18);
INSERT INTO role_permissions(fk_role, fk_permission) VALUES (7, 19);
INSERT INTO role_permissions(fk_role, fk_permission) VALUES (7, 20);
INSERT INTO role_permissions(fk_role, fk_permission) VALUES (7, 21);
INSERT INTO role_permissions(fk_role, fk_permission) VALUES (8, 22);
INSERT INTO role_permissions(fk_role, fk_permission) VALUES (8, 23);
INSERT INTO role_permissions(fk_role, fk_permission) VALUES (8, 24);
INSERT INTO role_permissions(fk_role, fk_permission) VALUES (9, 25);
INSERT INTO role_permissions(fk_role, fk_permission) VALUES (9, 26);
INSERT INTO role_permissions(fk_role, fk_permission) VALUES (9, 27);
INSERT INTO role_permissions(fk_role, fk_permission) VALUES (10, 28);
INSERT INTO role_permissions(fk_role, fk_permission) VALUES (10, 29);
INSERT INTO role_permissions(fk_role, fk_permission) VALUES (10, 30);
INSERT INTO role_permissions(fk_role, fk_permission) VALUES (11, 31);
INSERT INTO role_permissions(fk_role, fk_permission) VALUES (11, 32);
INSERT INTO role_permissions(fk_role, fk_permission) VALUES (11, 33);
INSERT INTO role_permissions(fk_role, fk_permission) VALUES (12, 34);
INSERT INTO role_permissions(fk_role, fk_permission) VALUES (12, 35);
INSERT INTO role_permissions(fk_role, fk_permission) VALUES (12, 36);
INSERT INTO role_permissions(fk_role, fk_permission) VALUES (13, 37);
INSERT INTO role_permissions(fk_role, fk_permission) VALUES (13, 38);
INSERT INTO role_permissions(fk_role, fk_permission) VALUES (13, 39);
INSERT INTO role_permissions(fk_role, fk_permission) VALUES (14, 40);
INSERT INTO role_permissions(fk_role, fk_permission) VALUES (14, 41);
INSERT INTO role_permissions(fk_role, fk_permission) VALUES (14, 42);
INSERT INTO role_permissions(fk_role, fk_permission) VALUES (15, 43);
INSERT INTO role_permissions(fk_role, fk_permission) VALUES (15, 44);
INSERT INTO role_permissions(fk_role, fk_permission) VALUES (15, 45);
INSERT INTO role_permissions(fk_role, fk_permission) VALUES (16, 46);
INSERT INTO role_permissions(fk_role, fk_permission) VALUES (16, 47);
INSERT INTO role_permissions(fk_role, fk_permission) VALUES (16, 48);
INSERT INTO role_permissions(fk_role, fk_permission) VALUES (17, 49);

INSERT INTO usuario(email, first_name, last_name, login, senha) VALUES ('klebermo@gmail.com', 'Kleber', 'Mota', 'klebermo', 'a7f5306827af05dd0c3b689323403e81');
INSERT INTO role_members(fk_usuario, fk_role) VALUES (1, 1);
INSERT INTO role_members(fk_usuario, fk_role) VALUES (1, 2);
INSERT INTO role_members(fk_usuario, fk_role) VALUES (1, 3);
INSERT INTO role_members(fk_usuario, fk_role) VALUES (1, 4);
INSERT INTO role_members(fk_usuario, fk_role) VALUES (1, 5);
INSERT INTO role_members(fk_usuario, fk_role) VALUES (1, 6);
INSERT INTO role_members(fk_usuario, fk_role) VALUES (1, 7);
INSERT INTO role_members(fk_usuario, fk_role) VALUES (1, 8);
INSERT INTO role_members(fk_usuario, fk_role) VALUES (1, 9);
INSERT INTO role_members(fk_usuario, fk_role) VALUES (1, 10);
INSERT INTO role_members(fk_usuario, fk_role) VALUES (1, 11);
INSERT INTO role_members(fk_usuario, fk_role) VALUES (1, 12);
INSERT INTO role_members(fk_usuario, fk_role) VALUES (1, 13);
INSERT INTO role_members(fk_usuario, fk_role) VALUES (1, 14);
INSERT INTO role_members(fk_usuario, fk_role) VALUES (1, 15);
INSERT INTO role_members(fk_usuario, fk_role) VALUES (1, 16);
INSERT INTO role_members(fk_usuario, fk_role) VALUES (1, 17);
 